# Use docker-compose to run both Express and Nginx
version: '3.8'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - express
